@startuml system-flow_enter-test-result-code

Actor User

group Editing
User -> "Web App": edit track
"Web App" <- "Web App": generates audio and video blobs

User -> "Web App": [optional] create transcript
"Web App" -> "createTranscript API": passes blob information
"createTranscript API" <- "createTranscript API": generate transcript
"Transcript Blob Storage" <- "createTranscript API": [success] store file
"Web App" <- "Transcript Blob Storage": [success] confirms success
User <- "Web App": display transcript

...

User -> "Web App": [optional] edit transcript
"Web App" <- "Web App": update display
...

User -> "Web App": finish editing
"Web App" <- "Web App": generates audio and video blobs

"Web App" -> "convertMedia API": calls
"convertMedia API" <- "convertMedia API": convert blobs to single mp4
"Edited Blob Storage" <- "convertMedia API": [success] store file
"Web App" <- "Edited Blob Storage": [success] confirms success

"Web App" -> "uploadTranscript API": [if transcript] calls
"uploadTranscript API" -> "Transcript Blob Storage": uploads file
"Web App" <- "Transcript Blob Storage": [success] confirms success
User <- "Web App": opens download/upload accordion
end

@enduml