@startuml editing

Actor Developer

group Editing
Developer -> "Web App": edit track(s)
"Web App" <- "Web App": generate audio and video blobs

group [optional] Generate Transcript
Developer -> "Web App": select create transcript
"Web App" -> "createTranscript API": call (audio blob)
"createTranscript API" <- "createTranscript API": generate transcript
"Transcript Blob Storage" <- "createTranscript API": [success] store (transcript)
"Web App" <- "Transcript Blob Storage": [success] response 200 OK
Developer <- "Web App": display transcript
end

group [optional] Edit Transcript
Developer -> "Web App": edit transcript
"Web App" <- "Web App": update display
end

Developer -> "Web App": finish editing
"Web App" <- "Web App": generate audio and video blobs

"Web App" -> "convertMedia API": call (audio blob, video blob)
"convertMedia API" <- "convertMedia API": convert blobs to single mp4
"Edited Blob Storage" <- "convertMedia API": [success] store (mp4)
"Web App" <- "Edited Blob Storage": [success] response 200 OK

"Web App" -> "uploadTranscript API": [if transcript] call (transcript)
"uploadTranscript API" -> "Transcript Blob Storage": upload (transcript)
"Web App" <- "Transcript Blob Storage": [success] response 200 OK
Developer <- "Web App": open download/upload accordion
end

@enduml