@startuml sign-up

Actor "Product Manager"

group Sign-up for Feedback
"Product Manager" -> "Web App": enter Google login details
"Web App" -> "Google Auth0 Server": call (username, password)
"Google Auth0 Server" <- "Google Auth0 Server": authorise user
"Web App" <- "Google Auth0 Server": [success] return access token
"Product Manager" <- "Web App": display modal
"Product Manager" -> "Web App": submit company name
"Web App" -> "Companies Database": insert (username, company name)
"Companies Database" <- "Companies Database": update table
"Web App" <- "Companies Database": [success] message OK
end

@enduml