@startuml sign-up

Actor "Product Manager"

group Feedback Sign-up
"Product Manager" -> "Web App": submit email and company name
"Web App" -> "Companies Database": insert (email, company name)
"Companies Database" <- "Companies Database": update table
"Web App" <- "Companies Database": [success] message OK
end

@enduml